### ISSUE TITLE
Update dependencies list with React@17

### ISSUE THREAD

**Issue by vanduc1102** [alexandre-lelain/components-extra#35]
Hi, is there any plan to keep up with React@17, I am having these warnings
```
warning " > components-extra@3.1.3" has incorrect peer dependency "react@^16.13.1".
warning " > components-extra@3.1.3" has incorrect peer dependency "react-dom@^16.13.1".
warning " > components-extra@3.1.3" has unmet peer dependency "styled-components@^5.1.1".
```

**Comment by alexandre-lelain** [comment]
Hello!

Thank you for the feedback. I'll provide a PR to upgrade those dependencies :+1:

**Comment by alexandre-lelain** [comment]
Hey @vanduc1102, [components-extra@3.2.1](https://www.npmjs.com/package/components-extra/v/3.2.1) was just released with react deps updated :)
