### ISSUE TITLE
Any plans for MUI5 support?

### ISSUE THREAD

**Issue by a-haan** [alexandre-lelain/components-extra#42]
Thanks for the package, I've just migrated to MUI5 and I was wondering if you plan on supporting it in the future?

**Comment by alexandre-lelain** [comment]
Hello, thank you for your feedback! 

Yes, I'm planning to migrate to MUI5 in the future, it will be in the v4 of components-extra :)

**Comment by a-haan** [comment]
Amazing, looking forward to it!
